export const TELEGRAM_COMMAND_CATALOG = [
  { command: "status", description: "查看当前状态" },
  { command: "continue_", description: "发送 continue" },
  { command: "stop", description: "中止当前任务" },
  { command: "clear", description: "中止任务并清空队列" },
  { command: "loop", description: "循环执行：/loop <prompt>" },
  { command: "mode", description: "切换执行模式 plan/act" },
  { command: "plan", description: "切换为计划模式" },
  { command: "act", description: "切换为执行模式" },
  { command: "tasks", description: "查看并发任务面板" },
  { command: "history", description: "查看最近任务历史" },
  { command: "task", description: "查看任务详情 /task <id>" },
  { command: "approvals", description: "查看待审批列表与批量操作" },
  { command: "checkpoint", description: "查看/恢复 checkpoint" },
  { command: "context", description: "查看上下文占用" },
  { command: "compact", description: "触发上下文压缩" },
  { command: "rewind", description: "按 checkpoint/prompt 回滚" },
  { command: "memory", description: "记忆中心 status/on/off/add" },
  { command: "agents", description: "查看或删除子代理" },
  { command: "style", description: "输出风格 show/list/set" },
  { command: "permissions", description: "查看权限规则与 sandbox" },
  { command: "statusline", description: "查看/设置状态栏" },
  { command: "skill", description: "调用技能 /skill <name>" },
  { command: "skills", description: "列出可用技能" },
  { command: "config", description: "打开配置（透传）" },
  { command: "model", description: "切换模型（透传）" },
  { command: "cost", description: "查看成本统计（透传）" },
  { command: "doctor", description: "诊断安装（透传）" },
  { command: "usage", description: "查看配额与限制（透传）" },
  { command: "theme", description: "切换主题（透传）" },
  { command: "plugin", description: "插件管理（透传）" },
  { command: "mcp", description: "MCP 管理（透传）" },
  { command: "review", description: "PR Review（透传）" },
  { command: "sandbox", description: "沙箱切换（透传）" },
  { command: "reload_plugins", description: "重载插件（透传 /reload-plugins）" },
  { command: "bug", description: "反馈问题（透传 /feedback）" },
  { command: "quit", description: "退出会话（透传 /exit）" },
  { command: "cwd", description: "查看/切换工作目录" },
  { command: "probe", description: "探活并查看快照" },
  { command: "resume", description: "选择并恢复历史会话" },
  { command: "approve", description: "批准审批（支持附带ID）" },
  { command: "reject", description: "拒绝审批（支持附带ID）" },
] as const;
