use relay_protocol::{
    message_type_defs, AckMessage, AckState, DeviceRole, Envelope, MAX_ENVELOPE_BINARY_PAYLOAD_BYTES,
    MAX_ENVELOPE_STRING_PAYLOAD_CHARS, PROTOCOL_VERSION, DEFAULT_NAMESPACE, WS_EVENT_TYPES,
    WsErrorPayload, WsFrame, WsHelloPayload, WsPresenceDevice, WsPresencePayload,
};
use std::{env, fs, path::PathBuf};
use ts_rs::TS;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: xtask generate-relay-protocol");
        return Ok(());
    }

    match args[1].as_str() {
        "generate-relay-protocol" => generate_relay_protocol(),
        _ => {
            eprintln!("Unknown command: {}", args[1]);
            Ok(())
        }
    }
}

fn generate_relay_protocol() -> Result<(), Box<dyn std::error::Error>> {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let root = manifest_dir
        .parent()
        .and_then(|path| path.parent())
        .ok_or("failed to resolve repo root")?;
    let out_path = root.join("packages/shared/src/generated/relay-protocol.ts");
    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }

    let mut output = String::new();
    output.push_str("// Generated by xtask generate-relay-protocol. DO NOT EDIT.\n");
    output.push_str("/* eslint-disable */\n\n");
    output.push_str(&format!("export const PROTOCOL_VERSION = \"{}\";\n", PROTOCOL_VERSION));
    output.push_str(&format!("export const DEFAULT_NAMESPACE = \"{}\";\n", DEFAULT_NAMESPACE));
    output.push_str(&format!(
        "export const MAX_ENVELOPE_STRING_PAYLOAD_CHARS = {};\n",
        MAX_ENVELOPE_STRING_PAYLOAD_CHARS
    ));
    output.push_str(&format!(
        "export const MAX_ENVELOPE_BINARY_PAYLOAD_BYTES = {};\n",
        MAX_ENVELOPE_BINARY_PAYLOAD_BYTES
    ));
    output.push_str("export const WS_EVENT_TYPES = [");
    for (idx, value) in WS_EVENT_TYPES.iter().enumerate() {
        if idx > 0 {
            output.push_str(", ");
        }
        output.push('"');
        output.push_str(value);
        output.push('"');
    }
    output.push_str("] as const;\n");
    output.push_str("export type WsEventType = typeof WS_EVENT_TYPES[number];\n\n");

    output.push_str("export const MessageType = {\n");
    for def in message_type_defs() {
        output.push_str("  ");
        output.push_str(def.name);
        output.push_str(": \"");
        output.push_str(def.value);
        output.push_str("\",\n");
    }
    output.push_str("} as const;\n");
    output.push_str("export type MessageType = typeof MessageType[keyof typeof MessageType];\n\n");

    output.push_str(
        "export type EnvelopePayload = string | Uint8Array | ArrayBuffer | { type: \"Buffer\"; data: number[] };\n\n",
    );

    output.push_str(&export_decl::<AckState>());
    output.push_str(&export_decl::<DeviceRole>());
    output.push_str(&export_decl::<AckMessage>());
    output.push_str(&export_decl::<Envelope>());
    output.push_str(&export_decl::<WsHelloPayload>());
    output.push_str(&export_decl::<WsPresenceDevice>());
    output.push_str(&export_decl::<WsPresencePayload>());
    output.push_str(&export_decl::<WsErrorPayload>());
    output.push_str(&export_decl::<WsFrame>());

    fs::write(&out_path, output)?;
    println!("Generated {}", out_path.display());
    Ok(())
}

fn export_decl<T: TS>() -> String {
    let mut decl = T::decl();
    let trimmed = decl.trim_start();
    if !trimmed.starts_with("export ") {
        decl = format!("export {decl}");
    }
    if !decl.ends_with('\n') {
        decl.push('\n');
    }
    decl.push('\n');
    decl
}
